/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.view;

import com.mycompany.controller.UrnaC;
import com.mycompany.model.Candidato;



/**
 *
 * @author dejae
 */
public class Urna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Urna.class.getName());

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        telaDaUrna = new javax.swing.JPanel();
        labelNumDigitado1 = new javax.swing.JLabel();
        labelNumDigitado2 = new javax.swing.JLabel();
        labelNumDigitado4 = new javax.swing.JLabel();
        labelNumDigitado5 = new javax.swing.JLabel();
        labelNumDigitado3 = new javax.swing.JLabel();
        lblVereador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelN = new javax.swing.JLabel();
        jLabelPT = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblPartidoCandidato = new javax.swing.JLabel();
        lblCandidatoImg = new javax.swing.JLabel();
        jLabelVC = new javax.swing.JLabel();
        jLabeLConfirmacaoVoto = new javax.swing.JLabel();
        btnVerSantinho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        painelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelBotoes.setForeground(new java.awt.Color(255, 255, 255));

        num1.setBackground(new java.awt.Color(51, 51, 51));
        num1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num1.setForeground(new java.awt.Color(255, 255, 255));
        num1.setText("1");
        num1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num2.setBackground(new java.awt.Color(51, 51, 51));
        num2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num2.setForeground(new java.awt.Color(255, 255, 255));
        num2.setText("2");
        num2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num3.setBackground(new java.awt.Color(51, 51, 51));
        num3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num3.setForeground(new java.awt.Color(255, 255, 255));
        num3.setText("3");
        num3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num4.setBackground(new java.awt.Color(51, 51, 51));
        num4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num4.setForeground(new java.awt.Color(255, 255, 255));
        num4.setText("4");
        num4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num5.setBackground(new java.awt.Color(51, 51, 51));
        num5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num5.setForeground(new java.awt.Color(255, 255, 255));
        num5.setText("5");
        num5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num6.setBackground(new java.awt.Color(51, 51, 51));
        num6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num6.setForeground(new java.awt.Color(255, 255, 255));
        num6.setText("6");
        num6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num7.setBackground(new java.awt.Color(51, 51, 51));
        num7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num7.setForeground(new java.awt.Color(255, 255, 255));
        num7.setText("7");
        num7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num8.setBackground(new java.awt.Color(51, 51, 51));
        num8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num8.setForeground(new java.awt.Color(255, 255, 255));
        num8.setText("8");
        num8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num9.setBackground(new java.awt.Color(51, 51, 51));
        num9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num9.setForeground(new java.awt.Color(255, 255, 255));
        num9.setText("9");
        num9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        num0.setBackground(new java.awt.Color(51, 51, 51));
        num0.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        num0.setForeground(new java.awt.Color(255, 255, 255));
        num0.setText("0");
        num0.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnBranco.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnBranco.setText("Branco");
        btnBranco.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnCorrige.setBackground(new java.awt.Color(255, 204, 51));
        btnCorrige.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCorrige.setText("Corrige");
        btnCorrige.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnConfirma.setBackground(new java.awt.Color(0, 182, 39));
        btnConfirma.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnConfirma.setText("Confirma");
        btnConfirma.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(num1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        telaDaUrna.setBackground(new java.awt.Color(255, 255, 255));
        telaDaUrna.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNumDigitado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNumDigitado1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelNumDigitado2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumDigitado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNumDigitado4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumDigitado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNumDigitado5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumDigitado5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelNumDigitado3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNumDigitado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblVereador.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblVereador.setText("Vereador");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Número:");

        jLabelN.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelN.setText("Nome:");

        jLabelPT.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelPT.setText("Partido:");

        lblNomeCandidato.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblPartidoCandidato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabelVC.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelVC.setText("FIM");

        jLabeLConfirmacaoVoto.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N

        javax.swing.GroupLayout telaDaUrnaLayout = new javax.swing.GroupLayout(telaDaUrna);
        telaDaUrna.setLayout(telaDaUrnaLayout);
        telaDaUrnaLayout.setHorizontalGroup(
            telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDaUrnaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelVC, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(lblVereador))
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(23, 23, 23)
                                        .addComponent(labelNumDigitado1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNumDigitado2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNumDigitado3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNumDigitado4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelNumDigitado5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPT)
                                            .addComponent(jLabelN))
                                        .addGap(26, 26, 26)
                                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblNomeCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                            .addComponent(lblPartidoCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(16, 16, 16)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabeLConfirmacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCandidatoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        telaDaUrnaLayout.setVerticalGroup(
            telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel3))
                                    .addComponent(labelNumDigitado1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNumDigitado2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(lblVereador)
                                .addGap(48, 48, 48)
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNumDigitado3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNumDigitado4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNumDigitado5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDaUrnaLayout.createSequentialGroup()
                        .addComponent(jLabeLConfirmacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabelVC)
                .addGap(5, 5, 5)
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelN)
                    .addComponent(lblNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPartidoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPT))
                .addGap(0, 206, Short.MAX_VALUE))
            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblCandidatoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerSantinho.setBackground(new java.awt.Color(1, 61, 111));
        btnVerSantinho.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnVerSantinho.setForeground(new java.awt.Color(255, 255, 255));
        btnVerSantinho.setText("Ver Santinho");
        btnVerSantinho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnVerSantinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSantinhoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\232.976684\\Downloads\\Projeto-da-urna-main\\Projeto-da-urna-main\\SimulacaoUrna\\src\\main\\Resource\\img\\semaijus.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaDaUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnVerSantinho, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telaDaUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(btnVerSantinho, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSantinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSantinhoActionPerformed
        // TODO add your handling code here:
        
    Santinho santinho = new Santinho();
    santinho.setVisible(true);
    santinho.setLocationRelativeTo(this);



    }//GEN-LAST:event_btnVerSantinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Urna().setVisible(true));
       
    // Criação e exibição da view + instanciando o controller
    java.awt.EventQueue.invokeLater(() -> {
        Urna view = new Urna();           // cria a view (a interface gráfica)
        UrnaC controller = new UrnaC(view); // passa a view para o controller
        view.setVisible(true);           // exibe a view (depois que o controller estiver pronto, se necessário)
    });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnVerSantinho;
    private javax.swing.JLabel jLabeLConfirmacaoVoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelPT;
    private javax.swing.JLabel jLabelVC;
    private javax.swing.JLabel labelNumDigitado1;
    private javax.swing.JLabel labelNumDigitado2;
    private javax.swing.JLabel labelNumDigitado3;
    private javax.swing.JLabel labelNumDigitado4;
    private javax.swing.JLabel labelNumDigitado5;
    private javax.swing.JLabel lblCandidatoImg;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblPartidoCandidato;
    private javax.swing.JLabel lblVereador;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel telaDaUrna;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getLabelNumDigitado1() {
    return labelNumDigitado1;
}

public javax.swing.JLabel getLabelNumDigitado2() {
    return labelNumDigitado2;
}

public javax.swing.JLabel getLabelNumDigitado3() {
    return labelNumDigitado3;
}

public javax.swing.JLabel getLabelNumDigitado4() {
    return labelNumDigitado4;
}

public javax.swing.JLabel getLabelNumDigitado5() {
    return labelNumDigitado5;
}

public javax.swing.JButton getNum0() {
    return num0;
}

public javax.swing.JButton getNum1() {
    return num1;
}

public javax.swing.JButton getNum2() {
    return num2;
}

public javax.swing.JButton getNum3() {
    return num3;
}

public javax.swing.JButton getNum4() {
    return num4;
}

public javax.swing.JButton getNum5() {
    return num5;
}

public javax.swing.JButton getNum6() {
    return num6;
}

public javax.swing.JButton getNum7() {
    return num7;
}

public javax.swing.JButton getNum8() {
    return num8;
}

public javax.swing.JButton getNum9() {
    return num9;
}
public javax.swing.JButton getBtnBranco() {
    return btnBranco;
}

public javax.swing.JButton getBtnCorrige() {
    return btnCorrige;
}

public javax.swing.JButton getBtnConfirma() {
    return btnConfirma;
}
public javax.swing.JLabel getLblCandidatoImg() {
    return lblCandidatoImg;
}

public void setLblCandidatoImg(javax.swing.JLabel lblCandidatoImg) {
    this.lblCandidatoImg = lblCandidatoImg;
}

public javax.swing.JLabel getLblNomeCandidato() {
    return lblNomeCandidato;
}

public void setLblNomeCandidato(javax.swing.JLabel lblNomeCandidato) {
    this.lblNomeCandidato = lblNomeCandidato;
}

public javax.swing.JLabel getLblPartidoCandidato() {
    return lblPartidoCandidato;
}

public void setLblPartidoCandidato(javax.swing.JLabel lblPartidoCandidato) {
    this.lblPartidoCandidato = lblPartidoCandidato;
}

}
