/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.view;

import com.mycompany.controller.UrnaController;



/**
 *
 * @author dejae
 */
public class Urna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Urna.class.getName());

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBotoes = new javax.swing.JPanel();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        telaDaUrna = new javax.swing.JPanel();
        labelPosicao0 = new javax.swing.JLabel();
        labelPosicao1 = new javax.swing.JLabel();
        labelPosicao2 = new javax.swing.JLabel();
        labelPosicao3 = new javax.swing.JLabel();
        labelPosicao4 = new javax.swing.JLabel();
        lblVereador = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelPT = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblPartidoCandidato = new javax.swing.JLabel();
        lblCandidatoImg = new javax.swing.JLabel();
        jLabelStatusVoto = new javax.swing.JLabel();
        jLabeLConfirmacaoVoto = new javax.swing.JLabel();
        btnVerSantinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        painelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        painelBotoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        painelBotoes.setForeground(new java.awt.Color(255, 255, 255));

        btnNum1.setBackground(new java.awt.Color(51, 51, 51));
        btnNum1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum1.setForeground(new java.awt.Color(255, 255, 255));
        btnNum1.setText("1");
        btnNum1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum2.setBackground(new java.awt.Color(51, 51, 51));
        btnNum2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum2.setForeground(new java.awt.Color(255, 255, 255));
        btnNum2.setText("2");
        btnNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum3.setBackground(new java.awt.Color(51, 51, 51));
        btnNum3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum3.setForeground(new java.awt.Color(255, 255, 255));
        btnNum3.setText("3");
        btnNum3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum4.setBackground(new java.awt.Color(51, 51, 51));
        btnNum4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum4.setForeground(new java.awt.Color(255, 255, 255));
        btnNum4.setText("4");
        btnNum4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum5.setBackground(new java.awt.Color(51, 51, 51));
        btnNum5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum5.setForeground(new java.awt.Color(255, 255, 255));
        btnNum5.setText("5");
        btnNum5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum6.setBackground(new java.awt.Color(51, 51, 51));
        btnNum6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum6.setForeground(new java.awt.Color(255, 255, 255));
        btnNum6.setText("6");
        btnNum6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum7.setBackground(new java.awt.Color(51, 51, 51));
        btnNum7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum7.setForeground(new java.awt.Color(255, 255, 255));
        btnNum7.setText("7");
        btnNum7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum8.setBackground(new java.awt.Color(51, 51, 51));
        btnNum8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum8.setForeground(new java.awt.Color(255, 255, 255));
        btnNum8.setText("8");
        btnNum8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum9.setBackground(new java.awt.Color(51, 51, 51));
        btnNum9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum9.setForeground(new java.awt.Color(255, 255, 255));
        btnNum9.setText("9");
        btnNum9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnNum0.setBackground(new java.awt.Color(51, 51, 51));
        btnNum0.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnNum0.setForeground(new java.awt.Color(255, 255, 255));
        btnNum0.setText("0");
        btnNum0.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnBranco.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnBranco.setText("Branco");
        btnBranco.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnCorrige.setBackground(new java.awt.Color(255, 204, 51));
        btnCorrige.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCorrige.setText("Corrige");
        btnCorrige.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        btnConfirma.setBackground(new java.awt.Color(0, 182, 39));
        btnConfirma.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnConfirma.setText("Confirma");
        btnConfirma.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.black));

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNum1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBotoesLayout.createSequentialGroup()
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                        .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        telaDaUrna.setBackground(new java.awt.Color(255, 255, 255));
        telaDaUrna.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelPosicao0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelPosicao0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicao0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelPosicao1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelPosicao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelPosicao2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelPosicao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicao2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelPosicao3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelPosicao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicao3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelPosicao4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelPosicao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPosicao4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblVereador.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lblVereador.setText("Vereador");

        jLabelNumero.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelNumero.setText("Número:");

        jLabelName.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelName.setText("Nome:");

        jLabelPT.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelPT.setText("Partido:");

        lblNomeCandidato.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        lblPartidoCandidato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblCandidatoImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelStatusVoto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelStatusVoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabeLConfirmacaoVoto.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N

        javax.swing.GroupLayout telaDaUrnaLayout = new javax.swing.GroupLayout(telaDaUrna);
        telaDaUrna.setLayout(telaDaUrnaLayout);
        telaDaUrnaLayout.setHorizontalGroup(
            telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabeLConfirmacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386))
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPT)
                                    .addComponent(jLabelName))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDaUrnaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNumero)
                                .addGap(18, 18, 18)))
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNomeCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPartidoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                        .addComponent(labelPosicao0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelPosicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelPosicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblVereador))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPosicao3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelPosicao4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelStatusVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(lblCandidatoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        telaDaUrnaLayout.setVerticalGroup(
            telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDaUrnaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCandidatoImg, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(lblNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPartidoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPT)))
                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabeLConfirmacaoVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                        .addComponent(lblVereador)
                                        .addGap(17, 17, 17)
                                        .addGroup(telaDaUrnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelPosicao0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPosicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPosicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPosicao3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelPosicao4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaDaUrnaLayout.createSequentialGroup()
                                        .addComponent(jLabelNumero)
                                        .addGap(9, 9, 9))))
                            .addGroup(telaDaUrnaLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabelStatusVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerSantinho.setBackground(new java.awt.Color(1, 61, 111));
        btnVerSantinho.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnVerSantinho.setForeground(new java.awt.Color(255, 255, 255));
        btnVerSantinho.setText("Ver Santinho");
        btnVerSantinho.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        btnVerSantinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSantinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(telaDaUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnVerSantinho, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(telaDaUrna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addComponent(btnVerSantinho, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSantinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSantinhoActionPerformed
        // TODO add your handling code here:
        
    Santinho santinho = new Santinho();
    santinho.setVisible(true);
    santinho.setLocationRelativeTo(this);



    }//GEN-LAST:event_btnVerSantinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    java.awt.EventQueue.invokeLater(() -> {
        Urna view = new Urna();
        UrnaController controller = new UrnaController(view);
        view.setVisible(true);
    });
       
    }
    
    public void setQuadradinhosVisiveis(boolean visivel) {
    labelPosicao0.setVisible(visivel);
    labelPosicao1.setVisible(visivel);
    labelPosicao2.setVisible(visivel);
    labelPosicao3.setVisible(visivel);
    labelPosicao4.setVisible(visivel);
}
public void setVereadorVisible(boolean visivel) {
    lblVereador.setVisible(visivel);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnVerSantinho;
    private javax.swing.JLabel jLabeLConfirmacaoVoto;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelPT;
    private javax.swing.JLabel jLabelStatusVoto;
    private javax.swing.JLabel labelPosicao0;
    private javax.swing.JLabel labelPosicao1;
    private javax.swing.JLabel labelPosicao2;
    private javax.swing.JLabel labelPosicao3;
    private javax.swing.JLabel labelPosicao4;
    private javax.swing.JLabel lblCandidatoImg;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblPartidoCandidato;
    private javax.swing.JLabel lblVereador;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel telaDaUrna;
    // End of variables declaration//GEN-END:variables
public javax.swing.JLabel getLabelPosicao0() {
    return labelPosicao0;
}

public javax.swing.JLabel getLabelPosicao1() {
    return labelPosicao1;
}

public javax.swing.JLabel getLabelPosicao2() {
    return labelPosicao2;
}

public javax.swing.JLabel getLabelPosicao3() {
    return labelPosicao3;
}

public javax.swing.JLabel getLabelPosicao4() {
    return labelPosicao4;
}

public javax.swing.JButton getBtnNum0() {
    return btnNum0;
}

public javax.swing.JButton getBtnNum1() {
    return btnNum1;
}

public javax.swing.JButton getBtnNum2() {
    return btnNum2;
}

public javax.swing.JButton getBtnNum3() {
    return btnNum3;
}

public javax.swing.JButton getBtnNum4() {
    return btnNum4;
}

public javax.swing.JButton getBtnNum5() {
    return btnNum5;
}

public javax.swing.JButton getBtnNum6() {
    return btnNum6;
}

public javax.swing.JButton getBtnNum7() {
    return btnNum7;
}

public javax.swing.JButton getBtnNum8() {
    return btnNum8;
}

public javax.swing.JButton getBtnNum9() {
    return btnNum9;
}
public javax.swing.JButton getBtnBranco() {
    return btnBranco;
}

public javax.swing.JButton getBtnCorrige() {
    return btnCorrige;
}

public javax.swing.JButton getBtnConfirma() {
    return btnConfirma;
}
public javax.swing.JLabel getLblCandidatoImg() {
    return lblCandidatoImg;
}

public void setLblCandidatoImg(javax.swing.JLabel lblCandidatoImg) {
    this.lblCandidatoImg = lblCandidatoImg;
}

public javax.swing.JLabel getLblNomeCandidato() {
    return lblNomeCandidato;
}

public void setLblNomeCandidato(javax.swing.JLabel lblNomeCandidato) {
    this.lblNomeCandidato = lblNomeCandidato;
}

public javax.swing.JLabel getLblPartidoCandidato() {
    return lblPartidoCandidato;
}

public void setLblPartidoCandidato(javax.swing.JLabel lblPartidoCandidato) {
    this.lblPartidoCandidato = lblPartidoCandidato;
}
public javax.swing.JLabel getLabelStatusVoto() {
    return jLabelStatusVoto;
}

public void setLabelStatusVoto(javax.swing.JLabel labelStatusVoto) {
    this.jLabelStatusVoto = labelStatusVoto;
}

  
    

}
